# detailed_reason - 自动生成的配置文件
# 帮助模型更好地对逻辑内容进行推理

# 插件基本信息
[plugin]

# 插件名称
name = "detailed_reason"

# 插件版本
version = "1.0.0"

# 配置文件版本
config_version = "1.0.0"

# 是否启用插件
enabled = true

# 使用的模型
use_model = "replyer"


